# Generated by Django 3.2 on 2022-05-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.category'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.location'),
        ),
    ]
